{% set version = '3.0-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lmertest
  version: {{ version|replace("-", "_") }}

source:
  fn: lmerTest_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/lmerTest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lmerTest/lmerTest_{{ version }}.tar.gz
  sha256: 95e07c9e1b231ac14c379324570c5a387e1a6348aee51b673dc32ec474322a5e

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-ggplot2
    - r-lme4 >=1.1_10
    - r-numderiv
  run:
    - r-base
    - r-mass
    - r-ggplot2
    - r-lme4 >=1.1_10
    - r-numderiv

test:
  commands:
    - $R -e "library('lmerTest')"           # [not win]
    - "\"%R%\" -e \"library('lmerTest')\""  # [win]

about:
  home: https://github.com/runehaubo/lmerTestR
  license: GPL (>= 2)
  summary: Provides p-values in type I, II or III anova and summary tables for lmer model fits
    (cf. lme4) via Satterthwaite's degrees of freedom method. A Kenward-Roger method
    is also available via the pbkrtest package. Model selection methods include step,
    drop1 and anova-like tables for random effects (ranova). Methods for Least-Square
    means (LS-means) and tests of linear contrasts of fixed effects are also available.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
