# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "G76M9WTCip8VtUHldRTnmcebmrhhLSX3ezB7sjisO5dpbrdNbDVulLUNABtAbprLv9qPGYwCPJgmRcndiZ/OWlPejeeSVc/EsNKSayYUHMgwm83s+3LUg7ijF6x0P8+QaddasddJ2LIkd43P/hlNenmrbGnSHSsGV0/57xYjNLT+lnifz7K1Qjgxm/Na2a1EOOaD93aMXHJHEPN6Vqkxc1SelbqSsIwKCcaTfGNGnKBT8u3ZMBuLWtuHA+PNrjTClIi72SLstPAYwlFzC4PsnS/a87lo6dvCvh9xrEELSdED4y7eXJJFUwy+LKbT2a33Yh+vaSsxsqDNp3kki5AqSiOpYvLWH/QVuZi/M1vWnR9vIUsZHvxkj8cOXNB/ycj7IsC+kUQUVWP3BaoHCInfgwV/GZBxeTNVpBU6d/nuYkfLhKAMDk+Yn93MzQ/OjWqnz9Ff4eXBU2tF+mtKo1y/GaWAJcpDPYj4wDLcRuf2CsBxfOnSsGVICZel4FbsKI/0ExpkE/xvqmHxaqynWhzjURiP4/m25V9ARD0uv7ZiVd9KCG6ppa+ljO/3h6hNeh05I1obofXIzktB11bkckUfXkBHbYmv8tx4SnNRbq9s36n97ZNahAfe+JxIamL50VBkiloJH2r5ANqF/2lQWkNp00TyzJBFVJQEpo5OqsMbemo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
