appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: G76M9WTCip8VtUHldRTnmcebmrhhLSX3ezB7sjisO5dpbrdNbDVulLUNABtAbprLv9qPGYwCPJgmRcndiZ/OWlPejeeSVc/EsNKSayYUHMgwm83s+3LUg7ijF6x0P8+QaddasddJ2LIkd43P/hlNenmrbGnSHSsGV0/57xYjNLT+lnifz7K1Qjgxm/Na2a1EOOaD93aMXHJHEPN6Vqkxc1SelbqSsIwKCcaTfGNGnKBT8u3ZMBuLWtuHA+PNrjTClIi72SLstPAYwlFzC4PsnS/a87lo6dvCvh9xrEELSdED4y7eXJJFUwy+LKbT2a33Yh+vaSsxsqDNp3kki5AqSiOpYvLWH/QVuZi/M1vWnR9vIUsZHvxkj8cOXNB/ycj7IsC+kUQUVWP3BaoHCInfgwV/GZBxeTNVpBU6d/nuYkfLhKAMDk+Yn93MzQ/OjWqnz9Ff4eXBU2tF+mtKo1y/GaWAJcpDPYj4wDLcRuf2CsBxfOnSsGVICZel4FbsKI/0ExpkE/xvqmHxaqynWhzjURiP4/m25V9ARD0uv7ZiVd9KCG6ppa+ljO/3h6hNeh05I1obofXIzktB11bkckUfXkBHbYmv8tx4SnNRbq9s36n97ZNahAfe+JxIamL50VBkiloJH2r5ANqF/2lQWkNp00TyzJBFVJQEpo5OqsMbemo=}
bot:
  automerge: true
